### PR TITLE
Typofix2

### PR DESCRIPTION
**Pull request by guineveresaenger**
Same as #234 but without documentation update.

### CODE REVIEW

**Comment by xenophenes** [comment]
For some reason the "Publishing documentation" commit is there - looks like it was the one before the last one that contained the old version of Master?

**Comment by guineveresaenger** [comment]
Whoops - no idea how that happened. Sorry about that.
@xenophenes - PTAL

**Comment by xenophenes** [comment]
So sorry about how complicated this all was! Evidently I'll have to fix up the instructions for committing to the docs. :) @jmccormick2001 is going to close out this PR - I included your two commits in a PR I opened that causes the changes you made to be populated in the Hugo public documentation. Thanks very much for catching these typos and contributing!

**Comment by guineveresaenger** [comment]
Happy to help - thank you for your patience :)

**Pull request merged**
