### PR TITLE
[feature] add helm chart

### PR DESCRIPTION
**Pull request by rimusz**

### CODE REVIEW

**Comment by jmccormick2001** [comment]
thanks, I'll test this out.

**Comment by xenophenes** [comment]
Hi! Just checking in. Everything looks good, but the reason why we waited to merge this is because of the new release that came out today, 2.1. If you could update your example to match the new release we'll test this out once more and merge it. Thank you!

**Comment by rimusz** [comment]
hey, I already have new version for chart, will update the PR in the next few days

**Comment by xenophenes** [comment]
Great! Thanks for the update.

**Comment by chriswessels** [comment]
Thanks @rimusz!

**Comment by rimusz** [comment]
@xenophenes the chart is updated to 2.1, we already tested it at StackpointCloud

**Comment by xenophenes** [comment]
Excellent! Thanks for your contribution. @jmccormick2001 this looks ready to merge.

**Comment by rimusz** [comment]
we already offering it to clients in our solutions :-)
screenshot 2017-11-07 17 24 29

**Comment by rimusz** [comment]
yay

**Pull request merged**
