### PR TITLE
adding Postgres primary & replica cert to Secret

### PR DESCRIPTION
**Pull request by szelenka**
**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [x] Have you updated or added documentation for the change, as applicable?
 - [x] Have you tested your changes on all related environments with successful results, as applicable?
   - [x] Have you added automated tests?

**Type of Changes:**

 
 - [ ] New feature
 - [x] Bug fix
 - [ ] Documentation
 - [ ] Testing enhancement
 - [ ] Other

**What is the current behavior (link to any open issues here)?**

Add replica service SAN to TLS cert used, such that it's possible to perform SSL connections between pgBouncer directly to the read-replica(s): #3446 

**What is the new behavior (if this is a feature change)?**
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

Adding all DNS names for the replica service to the TLS cert generated for the PostgresCluster

**Other Information**:

With this change, it'd be possible to deploy a dedicated deployment that points directly to the Postgres replicas for read-only queries; such that you can segment read/write queries by pointing to a different service.

### CODE REVIEW

**Review by tony-landreth — APPROVED** [review]

**Comment by tony-landreth** [comment]
@szelenka Looks good. Thanks for your contribution!

**Comment by abbottmg** [comment]
Did this patch make it into 5.4.1? I have a fresh install on my k8s cluster and the cert only lists the primary service.

**Comment by szelenka** [comment]
@abbottmg if you can decode which git hash aligns to version "5.4.1" it's be easy to check. But AFAIK, the maintainers explicitly don't make this easy to find. @tony-landreth can you help us?

**Comment by abbottmg** [comment]
@szelenka Yeah I figured that was the reason behind no tags after the 4.7 release. While I get not showing exactly what's in the customer-track builds, it'd be nice to publish a tag for anything visible on the developer track, or even X releases behind that.

I've appreciated this project enough that it's on my shortlist to subscribe once my site is bringing in any money, but there's also not a publicly available minimum price, and it's too early to go pinging sales without a ballpark so :shrug:

**Comment by abbottmg** [comment]
@tony-landreth could you confirm whether this patch is live in 5.4.1? I ask only so I can know whether I need to file a bug against the patch not working.

**Comment by tjmoore4** [comment]
@abbottmg Thanks for reaching out! This patch is not yet release, but it is planned for a release this fall.

**Comment by abbottmg** [comment]
Setting a breadcrumb for anyone who happens upon this thread (real talk: for myself by the time I next get to revise my dependencies): This PR is [noted] (https://access.crunchydata.com/documentation/postgres-operator/latest/releases/5.5.x#550-changes) as shipping in release 5.5.0.

**Pull request merged**
