### PR TITLE
client-setup script improvement and adjusted/unified Quickstart and Operator tutorial

### PR DESCRIPTION
**Pull request by VladMasarik**
**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [x] Have you updated or added documentation for the change, as applicable?
 - [x] Have you tested your changes on all related environments with successful results, as applicable?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)
 - [x] Documentation

**What is the current behavior? (link to any open issues here)**
Currently the `client-setup.sh` script requests users to export 5 environment variables, but the documentation mentions only 4, omitting the `PATH`. Additionally, the `PGO_OPERATOR_NAMESPACE`, `PGO_NAMESPACE`, and `PGO_APISERVER_URL` are not mentioned in the `client-setup.sh` output nor the documentation, although they are needed for successful usage of the `pgo` CLI. Also, in the Quickstart tutorial there is a mention of Ansible, although I never used it during installation.

**What is the new behavior (if this is a feature change)?**
- The `client-setup.sh` requests the user to also export the `PGO_OPERATOR_NAMESPACE`, `PGO_NAMESPACE`, and `PGO_APISERVER_URL` environment variables.
- The `PGO_APISERVER_URL` variable is automatically constructed by exporting the IP address of `postgres-operator` service.
- The documentation of Quickstart and Postgres Operator tutorial is "unified/shortened" so that users have to follow only the export instructions from the `client-setup.sh` script.
- Replaced the Ansible text with `client-setup.sh` reference.

**Other information**:
I am fairly certain I missed something, or changed something incorrectly. I am not sure if the changes are actually better, but I also hope that it will lead to less confusion when you successfully install `pgo`, but forget to export other important variables. Any critique is very welcome! Thank you for creating such a great tool.

Related #2228

### CODE REVIEW

**Review by jkatz — COMMENTED** [review]
Thanks for the proposal.

There are some changes that I agree. Rather than try to go back and forth, I will create a separate patch based on this and assign you credit.

**Comment by VladMasarik** [comment]
@jkatz Was this somehow implemented, so that can I close this issue?

**Comment by VladMasarik** [comment]
ping @jkatz

**Comment by andrewlecuyer** [comment]
With the `master` branch now reflecting PGO v5, this PR is no longer applicable.  Additionally, this PR was submitted for PGO v4.5, which is no longer available/supported in the Crunchy Developer Portal.

Thank you for your submission, and feel free to reach out if you have any issues with PGO v5!

**Pull request closed without merging**
