### PR TITLE
fix pod type detection

### PR DESCRIPTION
**Pull request by Sayrus**
**Checklist:**

 
 - [X] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change, as applicable?
 - [ ] Have you tested your changes on all related environments with successful results, as applicable?

**Type of Changes:**

 
 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
#637 #641 

Everything is detected as a pgpool or a pgbouncer if one of them is on your cluster.

```
cluster : a-type-cluster (crunchy-postgres:centos7-11.2-2.3.1)
	pod : a-type-cluster-545559d9cf-ss5h9 (Running) on node-6 (1/1) (pgbouncer)
	pvc : a-type-cluster
	pvc : a-type-cluster-xlog
	pod : a-type-cluster-ceho-555c78cdcd-4frf6 (Running) on node-7 (1/1) (pgbouncer)
	pvc : a-type-cluster-ceho
	pvc : a-type-cluster-ceho-xlog
	pod : a-type-cluster-pgbouncer-8bb9cd499-v47vm (Running) on node-6 (1/1) (pgbouncer)
	pod : a-type-cluster-pgpool-54c6579f47-r5zkb (Running) on node-7 (1/1) (pgpool)
	pod : a-type-cluster-qhbh-67cd6fc7cd-qc5p5 (Running) on node-6 (1/1) (pgbouncer)
	pvc : a-type-cluster-qhbh
	pvc : a-type-cluster-qhbh-xlog
```

**What is the new behavior (if this is a feature change)?**
`show cluster` returns the right pod type
```
	pod : a-type-cluster-545559d9cf-ss5h9 (Running) on node-6 (1/1) (primary)
	pvc : a-type-cluster
	pvc : a-type-cluster-xlog
	pod : a-type-cluster-ceho-555c78cdcd-4frf6 (Running) on node-7 (1/1) (replica)
	pvc : a-type-cluster-ceho
	pvc : a-type-cluster-ceho-xlog
	pod : a-type-cluster-pgbouncer-8bb9cd499-v47vm (Running) on node-6 (1/1) (pgbouncer)
	pod : a-type-cluster-pgpool-54c6579f47-r5zkb (Running) on node-7 (1/1) (pgpool)
	pod : a-type-cluster-qhbh-67cd6fc7cd-qc5p5 (Running) on node-6 (1/1) (replica)
	pvc : a-type-cluster-qhbh
	pvc : a-type-cluster-qhbh-xlog
```
`service-name` is correctly assigned when using one of these two as it doesn't return early by detecting that it is a pgpool/pgbouncer pod. Hence it is possible to deploy a cluster

**Other information**:
I am using the LABEL_PRIMARY as it is the once used by `checkPostgresPods` before assigning a `service-name` but we might as well use the `service-name` itself as it is the current implementation.

### CODE REVIEW

**Comment by cahoonpwork** [comment]
@Sayrus If you could make the PR against the develop branch, I'll get the team to review it.
Thanks. Paul

**Comment by Sayrus** [comment]
@cahoonpwork Thanks, I did that.

I will take the opportunity to ask for the rationale behind the choice of using `LABEL_SERVICE_NAME` to identify replica and primary. I understood that services use it but is there a case where `LABEL_PRIMARY` won't match `LABEL_SERVICE_NAME`  or a case where a pod would not be in the right cluster therefore needing the full name?

**Comment by jmccormick2001** [comment]
yeah, we really can't identify something as a primary or replica based on the primary flag, this is due to failover where the primary label is not updated, the primary label currently is only valid for the initial cluster, the service-name is the better choice to key off of and know whether something is a primary or replica, during a failover that label gets updates, not the primary label....actually primary label will be going away eventually.

**Comment by Sayrus** [comment]
I will update `getType` to use the service name again.

> actually primary label will be going away eventually.

By going away do you mean the meaning or the label itself. If the primary label itself goes away, then checking for its existence in `isPostgresPod` is meaningless and I need to find another way to know if the pod is a PostgresPod.

Why is the deployment tagged with `crunchy-pgpool: true` / `crunchy-pgbouncer: true`. I haven't looked at the behaviour of PGBouncer but it does seem that PGPool target service-name / service-name-replica and not the pgpool label on the postgres deployment.
Maybe it would make sense use only these labels on the pgpool / pgbouncer deployments and not on cluster / cluster-replica?

**Comment by jmccormick2001** [comment]
I just merged in a change to remove the LABEL_PRIMARY altogether, that change is in develop branch as of this morning.

**Comment by Sayrus** [comment]
@jmccormick2001 I am currently testing the develop:latest.

The fact that `spec.selector` is not set makes it fail creating the deployment. I'm not sure why this doesn't work on PGO as manually applying the JSON works like a charm and adding `spec.selector` also works.

With that said, on the develop branch this PR is useless. 

> Maybe it would make sense use only these labels on the pgpool / pgbouncer deployments and not on cluster / cluster-replica?

It seems that this is the case on the develop branch. Except the error with kubeapi, it works like a charm. I'll do some testing and close this PR and my issue if there is no problem anymore. Thanks!

**Comment by Sayrus** [comment]
The develop branch works for me.

**Pull request closed without merging**
