### PR TITLE
code change to allow choice of files to include in the cmap

### PR DESCRIPTION
**Pull request by Conor-Quin**
**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included? This can be found in the behavior questions below.
 - [ ] Have you updated or added documentation for the change, as applicable? 
As crunchy does not offer a Helm deploy/install I don't feel as though a documentation update is needed. I  feel as though this fix would only benefit a Helm deploy/install as we can control more easily what goes in to the configmap.
 - [x] Have you tested your changes on all related environments with successful results, as applicable?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
Currently, when you want to customize the config files, all of the files need to be inserted in the configmap `pgo-config`

**What is the new behavior (if this is a feature change)?**
The new behavior allows for some of the config files to be put into the configmap and if they are not in the configmap, the default config files will be uesd.

**Other information**:

### CODE REVIEW

**Comment by Conor-Quin** [comment]
@andrewlecuyer can I get the status on this? 
I'm just wondering if this has a chance of getting into a release or if it will never be added in.
I need this feature for work I'm doing so I'll need to think of a separate workaround if it will never get in.

If there are any changes I can put in please let me know. I'm happy to help :+1:

**Comment by jkatz** [comment]
Hi @Conor-Quin - this will certainly be reviewed but as with many open source projects it may not be an immediate turnaround!

**Comment by andrewlecuyer** [comment]
@Conor-Quin, I am getting complication errors when I attempt to build your changes, specifically due to a missing return arg for function `LoadTemplate`.  Here are the errors:

```bash
$ make postgres-operator-image
go install postgres-operator.go
# github.com/crunchydata/postgres-operator/config
config/pgoconfig.go:830:5: not enough arguments to return
        have (error)
        want (*template.Template, error)
make: *** [postgres-operator] Error 2
```
...as well as:
```bash
$ make postgres-operator-image
go install postgres-operator.go
# github.com/crunchydata/postgres-operator/config
config/pgoconfig.go:836:4: not enough arguments to return
        have (error)
        want (*template.Template, error)
make: *** [postgres-operator] Error 2
```

**Comment by Conor-Quin** [comment]
@andrewlecuyer sorry about that I must've forgotten to commit the most recent code. I have built my own image and have confirmed it worked prior to the PR. Sorry about that it should be okay to build now. Thanks for this

**Comment by Conor-Quin** [comment]
@kssikora @andrewlecuyer would it be possible to get a time estimate as to when this will be approved/denied?
We will just need to think of a workaround if this doesn't get approved.

If there's anything else you need me to do please let me know.

Thanks for the help

**Comment by jkatz** [comment]
Hi @Conor-Quin,

After discussing with @andrewlecuyer our plan is to give this one more check and then commit. Our plan is to back patch it into the `REL_4_1` branch as well. The 4.1.1 release will be available in the next couple of weeks -- we are targeting the week after the PostgreSQL update release (which happens to be this week).

Thanks!

**Comment by jkatz** [comment]
Closed in favor of #1090 and #1091

**Comment by Conor-Quin** [comment]
@jkatz Thank you for all the help :+1:

**Pull request closed without merging**
