### PR TITLE
Remove helm

### PR DESCRIPTION
**Pull request by jmccormick2001**
**Checklist:**

 
 - [ ] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change, as applicable?
 - [ ] Have you tested your changes on all related environments with successful results, as applicable?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**

**What is the new behavior (if this is a feature change)?**

**Other information**:

### CODE REVIEW

**Comment by Scuilion** [comment]
Out of curiosity, what was the reasoning for removing helm?

**Comment by jmccormick2001** [comment]
I felt that the complexity of our installs was increasing and thought Ansible might handle that better in this case, so we thought it was worth a try to see how the ansible experience of installation would look, so far its pretty good I think.  That said, if someone wanted to pick up the Helm chart, make it work for the new 4.0 deployment styles, we'd certainly consider adding a helm chart back in.  We might do that still if enough customer/user interest in a helm chart surfaces.  thanks for the question.

**Comment by Scuilion** [comment]
Awesome, thanks for the insight. I was using the helm chart in version 3 but had to split it apart and make too many customization, so when I saw it missing I wasn't too shocked. 
I'll have to take a look at the Ansible stuff.

**Comment by obeyler** [comment]
@jmccormick2001 I'm sorry to see that the helm chart is not provided anymore. So at least there is almost one user that prefer Helm chart to ansible.

**Comment by tengzhuofei** [comment]
> 我感到安装的复杂性在增加，并且认为Ansible在这种情况下可能会更好地解决这个问题，因此我们认为值得一试，看看Ansible的安装体验如何，到目前为止，我认为它还不错。就是说，如果有人想要获取Helm图表，使其适用于新的4.0部署样式，我们当然会考虑重新添加一个Helm图表。如果对Helm图表有足够的客户/用户兴趣，我们仍然可以这样做表面。谢谢你的问题。

I want to a chart to helm install

**Comment by tengzhuofei** [comment]
I want to a 4.0 chart to adapting to helm install

**Pull request merged**
