### PR TITLE
set to python3

### PR DESCRIPTION
**Pull request by shaynecm**
set localhost to use python3 by default as this is more common moving forwards

**Checklist:**

 
 - [ ] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change, as applicable?
 - [ ] Have you tested your changes on all related environments with successful results, as applicable?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**

**What is the new behavior (if this is a feature change)?**

**Other information**:

### CODE REVIEW

**Comment by jkatz** [comment]
@shaynecm Have you tested this change? If so, in what environments?

**Comment by shaynecm** [comment]
Hi, I have tested in Centos8- so far it would make python 3.6+ a requirment but this is fairly standard now and moving forwards.

**Comment by jkatz** [comment]
CentOS 8 is still relatively new and not everyone has updated yet. Additionally, there are other platforms that are still using older versions of Python (and this is coming from a Pythonista who adamantly writes his apps in 3.6+). Even our currently containers are not on CentOS 8 / UBI 8 (though that is coming very soon)

That said, per the Ansible docs on Python [autodiscovery](https://docs.ansible.com/ansible/latest/reference_appendices/interpreter_discovery.html#interpreter-discovery) on the target machines (in this case, the target is the machine itself), it seems like a e better answer is to do:

```
- localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python"
+ localhost ansible_connection=local
```

This would need to also change in the [inventory file for the container installer](https://github.com/CrunchyData/postgres-operator/blob/master/installers/image/inventory_template).

Also please be sure to adhere to [commit message guidelines](https://github.com/CrunchyData/postgres-operator/blob/master/CONTRIBUTING.md#commit-messages)

Thanks!

**Comment by jkatz** [comment]
@shaynecm Please let me know if you're planning to resubmit the patch -- we're actually working on stamping the beta release, and I'd like to include the change.

Thanks!

**Comment by shaynecm** [comment]
@jkatz, sorry I closed this pull request as I didn’t get the impression the code I wrote was wanted. 

It was just a small input I don’t want to do a massive write for adding a 3. I don’t have time to test on a number of platforms it was just an observation from trying to install your product. 

Feel free to carry it forwards if you want.

**Comment by jkatz** [comment]
@shaynecm It was wanted, just with some modifications :wink: We can also help with testing -- I was trying to get a better sense of the patch.

Some portion of this will make it's way into the next release.

Thanks!

**Pull request closed without merging**
